{% set name = "scilogger" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/scilogger-{{ version }}.tar.gz
  sha256: 6df23dfc1f34dc097f75f97e248e0e54e381c9063e0a593ca03ccb832144db5e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >68.2
    - wheel >0.41
    - setuptools-scm >7.1
    - pip
  run:
    - python >=3.9

test:
  imports:
    - scilogger
  requires:
    - pip

about:
  summary: SciLogger - Python Logging for Science
  description: |
    SciLogger is a Python Logging module. Specially targeted for scientific 
    applications. Use a global timer to measure the elapsed time. Provide a 
    class for timing code blocks. Definition of custom indentation levels. 
    Definition of colors for the logging levels.
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/scilogger
  dev_url: https://github.com/otvam/scilogger
  home: https://github.com/otvam/scilogger

extra:
  recipe-maintainers:
    - otvam
