{% set name = "scilogger" %}
{% set version = "1.2.4" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scilogger-{{ version }}.tar.gz
  sha256: d2882e339051431161e6821b722a4de987bf3c7797cffc20e7508ac26d57a6b0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.5
    - wheel >=0.45
    - setuptools-scm >=8.1
    - pip >=24.3
  run:
    - python >={{ python_min }}

test:
  imports:
    - scilogger
  requires:
    - python {{ python_min }}
    - pip >=24.3

about:
  summary: SciLogger - Logging for Scientific Applications
  description: |
    SciLogger is a extension of the Python Logging module. Specially targeted 
    for scientific applications. Use a global timer to measure the elapsed 
    time. Provide a class for timing code blocks. Definition of custom 
    indentation levels. Definition of colors for the logging levels.
  license: BSD-2-Clause
  license_file: LICENSE.txt
  doc_url: https://github.com/otvam/scilogger
  dev_url: https://github.com/otvam/scilogger
  home: https://github.com/otvam/scilogger

extra:
  recipe-maintainers:
    - otvam
